#### Snakemake parameters ####
keep-going: True ##### can be changed
latency-wait: 40
show-failed-logs: True
rerun-incomplete: True
restart-times: 2
reason: True
use-conda: True

#quiet: rule ---> show only job sent and if they fail, not progression report
#quiet: progress ---> sows the rules being sent to the cluster, but not their completion
quiet: rules
#cleanup_scripts:

#shadow: 'full'
#cores: 500
#max-jobs-per-second: 100
max-status-checks-per-second: 100

#Cluster submission

#slurm: True
jobs: 700

cluster: "sbatch -A {resources.group} -p {resources.partition} -N {resources.node} -J \"{rule}.{wildcards}\" -e \"logs/{rule}.{wildcards}.err\" -o \"logs/{rule}.{wildcards}.out\" -t {resources.runtime} --mem={resources.mem_mb}" # --cpus-per-task={threads}"

#default resources
default-resources:
  - group="korbel"
  #- cores=1
  - mem_mb=3000 # default is in MiB
  - partition="htc-el8" 
  #- list="bergamo"
  - node=1
  - runtime="1d"
  
#rules resources:
set-resources:
  - high_confident_filters:mem_mb=5000
  
  - Get_ME_from_annotation:mem_mb=5000
  
  - hisat2_genome_index:partition=bigmem
  - hisat2_genome_index:mem_mb=8000
  
  - Splice_Junction_Library:mem_mb=6000
  
  - Output:partition=bigmem
  - Output:mem_mb=30000
  - Output:cores=2
  
  - GetPWM:mem_mb=6000
  - Get_Genome:mem_mb=100
  
  - bowtie_genome_index:partition=bigmem
  - bowtie_genome_index:mem_mb=30000
  #- bowtie_genome_index:cores=2
  
  - download_fastq:partition=htc-el8
  - download_fastq:mem_mb=1000
  
  - whippet_index:partition=bigmem
  - whippet_index:mem_mb=32000
  #- whippet_index:cores=1
  #- whippet_index:list=naples
  
  - move_and_clean_psi:mem_mb=1200
  
  #- whippet_quant:mem_mb=16000
  #- whippet_quant:list=naples
  #- whippet_quant:partition=bigmem
  
  
  #- hisat2_to_Genome:cores=1
  - hisat2_to_Genome:mem_mb=32000
  - hisat2_to_Genome:partition=bigmem


#set-threads:
  #- hisat2_to_Genome=6
  #- hisat2_Genome_index=64

  
